export { default as MainSection } from './MainSection'
export { default as MainComponent, FlexWithTip } from './components'
export { default as MainSectionContext } from './context'
export * from './styles'
export * from './types'
